- name: variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Trainer: "Sivakumar"
    Duration: "120hrs"
  tasks: #list of tasks
    - name: print override information
      vars:
        Course: "Terraform"
      ansible.builtin.debug:
        msg: "Hello we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}"
    - name: print information
      ansible.builtin.debug:
        msg: "Hello we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}"
