- name: variables from files
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: please enter username
      private: false
    - name: PASSWORD
      prompt: please enter password
      private: true
  tasks: #list of tasks
    - name: print override information
      ansible.builtin.debug:
        msg: "Hi, Username:{{USERNAME}, Password is{{PASSWORD}}"
