- name: variables preference
  hosts: localhost
  vars:
    WISHES: "Morning from PLAY variable"
  vars_file:
    - vars.yaml
  vars_prompt:
    - name: WISHES
      prompt: Please enter Wishes
      private: false
  tasks: #list of tasks
    - name: get value from args
      ansible.builtin.debug:
        msg: "Hello, Good {{WISHES}}"
